# Generated by Django 3.1.8 on 2021-07-05 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_question', models.CharField(max_length=120)),
                ('card_answer', models.CharField(max_length=120)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flashcard.collection')),
            ],
        ),
    ]
